### ISSUE TITLE
A question about KPP (Kernel Patch Protection) on iOS.

### ISSUE THREAD

**Issue by Fadi5555** [jndok/iokit-dumper-arm64#1]
@jndok hi there. My question is the new jailbreak will defeat KPP? I mean not avoid it like pangu9 did.
Because this is so important to implement JIT to 64-bit device. Last time about having JIT support on 64-bit devices was on ios 8.4 (by TaiG jaibreak).
Anyway do you have any idea or plan how to defeat or patch KPP please?
because I saw your commits said kernel cache.
Thanks a lot.

**Comment by jndok** [comment]
No, I don't know how to defeat KPP and there is no public documentation about it. 

If you want to ask me any kind of question, please PM me and don't open issues on my projects, since this is not the right place to do so. Thanks :)
