### ISSUE TITLE
head is NULL

### ISSUE THREAD

**Issue by razygon** [jndok/iokit-dumper-arm64#2]
when the tool running SLIST_FOREACH(p, &head, entries), the head should already have all the kexts info, right?
but i checked via lldb, there's nothing in head.
The kernelcache is directly from /System/Library/Caches/com.apple.kernelcaches, without any other operation?

**Comment by jndok** [comment]
If the hierarchy list is empty, it means the tool hasn't found any class in the kernelcache, hence you are using an invalid kernelcache. You should use a kernel dump or a decrypted kernelcache.

You can get a decrypted kernelcache by downloading an OTA update, and uncompressing the kernelcache found in `/AssetData/boot/`. Here's [a short guide](https://www.reddit.com/r/jailbreak/comments/4nyz1p/discussion_decrypted_kernel_cache_ios_10/d48cgd7).

**Comment by razygon** [comment]
Thanks jndok, solved
