### ISSUE TITLE
how did you get the 64-bit kernel cache?

### ISSUE THREAD

**Issue by lilang-wu** [jndok/iokit-dumper-arm64#3]
Hi, 
As far as I know,  xpwntool only can decrypt the 32-bit kernelcache. could you give me some advise to decrypt the 64-bit kernelcache?

**Comment by jndok** [comment]
The new kernelcaches are already decrypted, just compressed. For older iOS versions, I simply used kernel dumps.

**Comment by lilang-wu** [comment]
I download the 10.0.3 ipsw, and try to unzip the  kernelcache.release.d10. however, I found it is not a compressed file. Then I use the lzssdec tool:
          lzssdec -o 448 <kernelcache.release.d10> kernel.dec
but IDA fail to distinguish kernel.dec as a kernelcache file. 
could you give me some advise? Thank you very much!
